### PR TITLE
First working draft of dispatching mechanism.

### PR DESCRIPTION
**Pull request by ecstasy2**

### CODE REVIEW

**Comment by ecstasy2** [comment]
@pcowgill just so we can do a code review before merging it.

**Comment by ecstasy2** [comment]
@pcowgill just referencing you on this PR so that you can eventually review it.

**Comment by pcowgill** [comment]
I dropped the ball on reviewing this before - I'll take a look now.

**Comment by pcowgill** [comment]
Done reviewing these commits.

**Pull request merged**
